// Code generated by mockery v2.0.3. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// IOtp is an autogenerated mock type for the IOtp type
type IOtp struct {
	mock.Mock
}

// GenerateOTP provides a mock function with given fields:
func (_m *IOtp) GenerateOTP() string {
	ret := _m.Called()

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}
