// Code generated by mockery v2.0.0-alpha.2. DO NOT EDIT.

package mocks

import (
	domain "github.com/DkreativeCoders/dmessanger-service/pkg/domain"

	mock "github.com/stretchr/testify/mock"

	time "time"
)

// ITokenService is an autogenerated mock type for the ITokenService type
type ITokenService struct {
	mock.Mock
}

// CreateTokenWithExpirationInHours provides a mock function with given fields: userID, uniqueID, expirationTimeInHour
func (_m *ITokenService) CreateTokenWithExpirationInHours(userID uint, uniqueID, otp string, expirationTimeInHour time.Duration) (*domain.Token, error) {
	ret := _m.Called(userID, uniqueID, expirationTimeInHour)

	var r0 *domain.Token
	if rf, ok := ret.Get(0).(func(uint, string, time.Duration) *domain.Token); ok {
		r0 = rf(userID, uniqueID, expirationTimeInHour)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Token)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(uint, string, time.Duration) error); ok {
		r1 = rf(userID, uniqueID, expirationTimeInHour)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// CreateTokenWithExpirationInMinutes provides a mock function with given fields: userID, uniqueID, expirationTimeInMinutes
func (_m *ITokenService) CreateTokenWithExpirationInMinutes(userID uint, uniqueID, otp string, expirationTimeInMinutes time.Duration) (*domain.Token, error) {
	ret := _m.Called(userID, uniqueID, expirationTimeInMinutes)

	var r0 *domain.Token
	if rf, ok := ret.Get(0).(func(uint, string, time.Duration) *domain.Token); ok {
		r0 = rf(userID, uniqueID, expirationTimeInMinutes)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Token)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(uint, string, time.Duration) error); ok {
		r1 = rf(userID, uniqueID, expirationTimeInMinutes)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
